capstone_project-django/eims/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from secretary.views import LandingPageView, ProfileView
from users.views import LoginView, LogoutView
from secretary.views import ExportCSVView




urlpatterns = [
    path('admin/', admin.site.urls), 
    path('', LandingPageView.as_view(), name="landing-page"),
    path('profile/', ProfileView.as_view(), name="profile"),
    path('item/', include('secretary.urls', namespace='secretary')),
    path('user/', include('users.urls', namespace='users')),
    path('room/', include('rooms.urls', namespace='rooms')),
    path('staffs/', include('staffs.urls', namespace='staffs')),
    path('equipment/', include('rlab.urls', namespace='equipments')),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('export-csv/', ExportCSVView.as_view(), name='export-csv'),
    
    

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

capstone_project-django/staffs/urls.py
from django.urls import path
from . views import (
    StaffListView, StaffDetailView, StaffCreateView, StaffUpdateView
)
app_name = 'staffs'

urlpatterns = [

        path('', StaffListView.as_view(), name='staff-list'),
        path('<int:pk>/', StaffDetailView.as_view(), name='staff-detail'),
        path('<int:pk>/update/', StaffUpdateView.as_view(), name='staff-update'),
        path('add/', StaffCreateView.as_view(), name='staff-create'),
]

capstone_project-django/staffs/models.py
from django.db import models

capstone_project-django/staffs/forms.py
from django import forms
from django.contrib.auth import get_user_model

User = get_user_model()

class StaffModelForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'department',
            'email',
            'contact_number',
            'password',

        ]

class StaffUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'department',
            'email',
            'contact_number',
        ]

capstone_project-django/staffs/views.py
from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect, render
from django.views import generic
from django.urls import reverse_lazy
from django.core.mail import send_mail
from django.contrib.auth.mixins import LoginRequiredMixin
from users.mixins import StaffRequiredMixin, AdminRequiredMixin
from django.contrib.auth import get_user_model
from .forms import StaffModelForm, StaffUpdateForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate

User = get_user_model()



class MyView(StaffRequiredMixin, generic.View):
    pass

class StaffListView(AdminRequiredMixin, generic.ListView):
    template_name = 'staffs/staff_list.html'
    model = User

    def get_queryset(self):
        return User.objects.filter(is_staff=True, is_secretary=False, is_dean=False)
    


class StaffCreateView(AdminRequiredMixin, generic.CreateView):
    form_class = StaffModelForm
    template_name = 'staffs/staff_create.html'
    success_url = reverse_lazy('staffs:staff-list')

    def form_valid(self, form):
    # Save the user
        user = form.save(commit=False)
        user.set_password(form.cleaned_data['password'])  # Hash the password
        user.is_staff = True
        user.save()

    # Send invitation email
        subject = "EIMS Capstone Invitation"
        message = "You are invited to be a Staff in EIMS Capstone"
        from_email = "eims@test.com"
        recipient_list = [user.email]
        send_mail(subject, message, from_email, recipient_list)

        return super().form_valid(form)


class StaffDetailView(AdminRequiredMixin,  generic.DetailView):
    template_name = 'staffs/staff_detail.html'
    context_object_name = 'staff'   
    
    def get_queryset(self):
        return User.objects.all()
    
class StaffUpdateView(AdminRequiredMixin, generic.UpdateView):
    model = User
    form_class = StaffUpdateForm
    template_name = 'staffs/staff_update.html'
    success_url = reverse_lazy('staffs:staff-list')

    def form_valid(self, form):
        messages.info(self.request, "You have successfully updated this User.")
        return super().form_valid(form)

capstone_project-django/staffs/templates/staffs/staff_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container mx-auto h-full flex justify-center items-center">
        <div class="max-w-md mx-auto">
            <h1 class="text-3xl font-semibold text-gray-800 mb-6">Add Item</h1>
            <form method="post" class="mx-auto">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded mt-4">Add</button>
            </form>
        </div>
    </div>
{% endblock content %}

capstone_project-django/staffs/templates/staffs/staff_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<section class="text-gray-700 body-font">
    <div class="container px-5 py-12 mx-auto">
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li class="mb-2 px-4 py-2 rounded-lg 
                    {% if message.tags == 'success' %}
                        bg-green-100 text-green-900 border-green-400
                    {% elif message.tags == 'error' %}
                        bg-red-100 text-red-900 border-red-400
                    {% elif message.tags == 'info' %}
                        bg-blue-100 text-blue-900 border-blue-400
                    {% elif message.tags == 'warning' %}
                        bg-yellow-100 text-yellow-900 border-yellow-400
                    {% endif %}
                ">
                    {{ message }}
                </li>
            {% endfor %} 
        </ul>
    {% endif %}
        <div class="flex justify-between items-center border-b border-gray-200 pb-6 mb-8">
            <h1 class="text-3xl font-semibold text-gray-800">Staffs</h1>
            <div class="flex items-center space-x-6">
                <a href="{% url 'staffs:staff-create' %}" class="text-indigo-500 hover:text-indigo-700">Add Staff</a>
            </div>
        </div>
        <div class="mb-8 flex items-center">
            <form method="GET" action="" class="flex items-center space-x-4">
                {% csrf_token %}
                <input type="text" name="search_term" placeholder="Search..." class="border rounded-l py-2 px-4 focus:outline-none focus:ring focus:border-blue-300">
                <button type="submit" class="bg-blue-500 text-white py-2 px-4 rounded-r hover:bg-blue-600">Search</button>
            </form>
        </div>
        
        <div class="overflow-x-auto">
            <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                <table class="min-w-full divide-y divide-gray-200">
                    <thead class="bg-gray-50">
                        <tr>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Username
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Firstname
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Lastname
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Deparment
                            </th>
                            {% if request.user.is_admin %}
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Action
                            </th>
                            {% endif %}
                        </tr>
                    </thead>
                    <tbody>
                        {% for user in object_list %}
                            <tr class="bg-white">
                                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                                    {{ user.username }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                                    {{ user.first_name }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                                    {{ user.last_name }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                                    {{ user.department }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                    <form method="get" action="{% url 'staffs:staff-update' user.pk %}">
                                        {% csrf_token %}
                                        <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Update</button>
                                    </form>
                                 </td>
                            </tr>
                        {% empty %}

                        <p>There are currently no Staff</p>

                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>
<script src="https://cdn.jsdelivr.net/npm/quagga/dist/quagga.min.js"></script>
{% endblock content %}

capstone_project-django/staffs/templates/staffs/staff_update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container mx-auto h-full flex justify-center items-center">
        <div class="max-w-md mx-auto">
            <h1 class="text-3xl font-semibold text-gray-800 mb-6">Update Staff</h1>
            <form method="post" class="mx-auto">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded mt-4">Save</button>
            </form>
        </div>
    </div>
{% endblock content %}