capstone_project-django/eims/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from secretary.views import LandingPageView, ProfileView
from users.views import LoginView, LogoutView
from secretary.views import ExportCSVView




urlpatterns = [
    path('admin/', admin.site.urls), 
    path('', LandingPageView.as_view(), name="landing-page"),
    path('profile/', ProfileView.as_view(), name="profile"),
    path('item/', include('secretary.urls', namespace='secretary')),
    path('user/', include('users.urls', namespace='users')),
    path('room/', include('rooms.urls', namespace='rooms')),
    path('staffs/', include('staffs.urls', namespace='staffs')),
    path('equipment/', include('rlab.urls', namespace='equipments')),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('export-csv/', ExportCSVView.as_view(), name='export-csv'),
    
    

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

capstone_project-django/secretary/urls.py
from django.urls import path
from . views import (
    ItemListView, ItemCreateView, ItemDetailView, ItemUpdateView, ItemDeleteView, 
    DashboardView, ItemBorrowView,  BorrowItemListView, AddUserView, ReturnItemView, ReturnedItemListView
    
)
from . import views

app_name = 'secretary'

urlpatterns = [
    path('', ItemListView.as_view(), name='item-list'),
    path('new/', ItemCreateView.as_view(), name='item-new'),
    path('<int:pk>/', ItemDetailView.as_view(), name='item-detail'),
    path('<int:pk>/update/', ItemUpdateView.as_view(), name='item-update'),
    path('<int:pk>/delete/', ItemDeleteView.as_view(), name='item-delete'),
    path('dashboard/', DashboardView.as_view(), name='item-dashboard'),
    path('borrow/', ItemBorrowView.as_view(), name='item-borrow'),
    path('borrowed/', BorrowItemListView.as_view(), name='borrowed-list'),
    path('return-item/<int:pk>/', ReturnItemView.as_view(), name='return-item'),
    path('returned-item/', ReturnedItemListView.as_view(), name='returned-list'),
    path('add user/', AddUserView.as_view(), name='add-user'),


]

capstone_project-django/secretary/models.py
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import AbstractUser
from django.dispatch import receiver
from django.utils import timezone
from django.contrib.auth import get_user_model
from django.utils.dateformat import format
import uuid


User = get_user_model()


class Category(models.Model):
    name = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return f"{self.name}"
    
class Item(models.Model):
    name = models.CharField(max_length=100, blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True)
    description = models.TextField(blank=True, null=True, max_length=1000)
    price = models.IntegerField(blank=True, null=True)
    quantity = models.IntegerField(default=1, blank=True, null=True)
    batch_id = models.CharField(max_length=50, blank=True, null=True)
    unique_identifier = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)  # Unique identifier field

    def save(self, *args, **kwargs):
        # Generate batch_id if not provided
        if not self.batch_id:
            self.batch_id = uuid.uuid4().hex  # Generate a unique batch ID using UUID
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.name}"
    
class BorrowedItem(models.Model):
    borrower = models.ForeignKey(User, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    date_borrowed = models.DateTimeField(auto_now_add=True)
    
    def return_item(self):

        # Add the quantity back to the item
        
        self.item.quantity += self.quantity  
        self.item.save()
        self.delete()

    def __str__(self):
        formatted_date = format(self.date_borrowed, 'N j, Y, P')
        return f"{self.borrower.username} borrowed {self.item.description} of  {self.quantity} of {self.item.name} on {formatted_date}"

class ReturnItemHistory(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    borrower = models.ForeignKey(User, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1, blank=True, null=True)
    date_returned = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        formatted_date = format(self.date_returned, 'N j, Y, P')
        return f"{self.item.name} by {self.borrower.username} was returned on {formatted_date}"
    

capstone_project-django/secretary/forms.py
from django import forms
from .models import Item, BorrowedItem
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model

User = get_user_model()

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['name', 'description', 'price', 'quantity', 'batch_id']

    def clean_name(self):
        name = self.cleaned_data.get('name')
        if not name:
            raise forms.ValidationError("Please enter an item name.")
        return name
    
    def clean_price(self):
        price = self.cleaned_data.get('price')
        if not price:
            raise forms.ValidationError("Please enter a price.")
        return price

    def clean_batch_id(self):
        batch_id = self.cleaned_data.get('batch_id')
        if not batch_id:
            raise forms.ValidationError("Please enter a batch ID.")
        return batch_id

class ItemUpdateForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['name', 'category', 'description', 'price', 'quantity', 'batch_id']
        
class ItemSearchForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['name', 'description', 'price', 'quantity', 'batch_id']


class BorrowItemForm(forms.ModelForm):
    class Meta:
        model = BorrowedItem
        fields = ['borrower', 'item', 'quantity']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['borrower'].queryset = User.objects.filter(is_staff=True, is_superuser=False, is_active=True)
        self.fields['item'].queryset = Item.objects.exclude(quantity=0)
        
    def clean_borrower(self):
        borrower = self.cleaned_data.get('borrower')
        if not borrower:
            raise forms.ValidationError("Only secretaries can borrow items.")
        return borrower
    
    def clean_item(self):
        item = self.cleaned_data.get('item')
        if not item:
            raise forms.ValidationError("Please select an item to borrow.")
        return item

class  UserCreateForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']
        

    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_secretary = self.cleaned_data['is_secretary']
        user.is_dean = self.cleaned_data['is_dean']
        user.is_staff = self.cleaned_data['is_staff']
        if commit:
            user.save()
        return user

capstone_project-django/secretary/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib import messages
from django.http import HttpResponse
from django.views import generic
from django.urls import reverse_lazy
from .models import Item, User, BorrowedItem, ReturnItemHistory
from .forms import ItemForm, BorrowItemForm, UserCreateForm, ItemSearchForm, ItemUpdateForm
from django.contrib.auth.mixins import LoginRequiredMixin
from users.mixins import DeanRequiredMixin, StaffRequiredMixin, SecretaryRequiredMixin
import barcode
from barcode.writer import ImageWriter
import tempfile
import os
import qrcode
from django.conf import settings



class LandingPageView(generic.TemplateView):
    template_name = 'landing_page.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect("profile")
        return super().dispatch(request, *args, **kwargs)
    
class ProfileView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'profile.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Add context data here
        context['user'] = self.request.user  # For example, adding the logged-in user object to the context
        return context

class ExportCSVView(generic.View):
    def get(self, request, *args, **kwargs):
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = 'attachment; filename="Items.csv"'

        writer = csv.writer(response)
        writer.writerow(['Column 1', 'Column 2', 'Column 3'])  # Add column headers

        queryset = Item.objects.all()  # Retrieve data from your model
        for obj in queryset:
            writer.writerow([obj.name, obj.description, obj.quantity, obj.price])  # Add data rows

        return response
class DashboardView(StaffRequiredMixin, generic.TemplateView):
    template_name = 'secretary/dashboard.html'

class ItemListView(SecretaryRequiredMixin, generic.ListView):
    template_name = 'secretary/item_list.html'
    queryset = Item.objects.all()
    form_class = ItemSearchForm  # Assign the form class to the view

    def get_queryset(self):
        queryset = super().get_queryset()  # Retrieve the original queryset

        # Check if a search term was submitted
        search_term = self.request.GET.get('search_term')
        if search_term:
            queryset = queryset.filter(name__icontains=search_term)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.form_class()  # Instantiate the form
        return context

class BorrowItemListView(SecretaryRequiredMixin, generic.ListView):
    template_name = 'secretary/borrowed_list.html'
    queryset = BorrowedItem.objects.all()

class ItemDetailView(SecretaryRequiredMixin, generic.DetailView):
    model = Item
    template_name = 'secretary/item_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        item = self.get_object()
        batch_items = Item.objects.filter(batch_id=item.batch_id)
        context['batch_items'] = batch_items
        return context
    
class ItemCreateView(SecretaryRequiredMixin, generic.CreateView):
    template_name = 'secretary/item_create.html'
    form_class = ItemForm
    success_url = reverse_lazy("secretary:item-list")

    
class ItemUpdateView(SecretaryRequiredMixin, generic.UpdateView):

    model = Item
    form_class = ItemUpdateForm
    template_name = 'secretary/item_update.html'
    success_url = reverse_lazy('secretary:item-list')

    def form_valid(self, form):
        messages.info(self.request, "You have successfully updated this item")
        return super().form_valid(form)


class ItemDeleteView(SecretaryRequiredMixin, generic.DeleteView):
    template_name = 'secretary/item_delete.html'
    model = Item
    success_url = reverse_lazy("secretary:item-list")

class ItemBorrowView(SecretaryRequiredMixin, generic.CreateView):
    template_name = 'secretary/item_borrow.html'
    form_class = BorrowItemForm
    success_url = reverse_lazy('secretary:borrowed-list')

    def form_valid(self, form):
        # Deduct the quantity from the item
        item = form.cleaned_data['item']
        quantity_borrowed = form.cleaned_data['quantity']

        if quantity_borrowed <= item.quantity:
            item.quantity -= quantity_borrowed
            item.save()

            # Save the borrowed item
            form.save()
            messages.success(self.request, 'Item borrowed successfully.')
            return super().form_valid(form)
        else:
            messages.error(self.request, 'Not enough quantity available.')
            return redirect('secretary:item-borrow')
        
class ReturnItemView(SecretaryRequiredMixin, generic.RedirectView):
        def get(self, request, *args, **kwargs):
            borrowed_item = get_object_or_404(BorrowedItem, pk=kwargs['pk'])
            borrower = borrowed_item.borrower
            returned_item = borrowed_item.item
            borrowed_item.return_item()
            ReturnItemHistory.objects.create(item=returned_item, borrower=borrower)
            messages.success(request, 'Item returned successfully.')
            return redirect('secretary:borrowed-list')
        
class ReturnedItemListView(SecretaryRequiredMixin, generic.ListView):
    template_name = 'secretary/return_history.html'
    queryset = ReturnItemHistory.objects.all()


    
class AddUserView(SecretaryRequiredMixin, generic.CreateView):
    template_name = 'secretary/add_user.html'
    form_class = UserCreateForm
    success_url = reverse_lazy("secretary:add-user")

capstone_project-django/secretary/templates/secretary/add_user.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <h1>Add User</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Add</button>
    </form>
{% endblock content %}

capstone_project-django/secretary/templates/secretary/borrowed_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<section class="text-gray-700 body-font">
    <div class="container px-5 py-12 mx-auto">
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li class="mb-2 px-4 py-2 rounded-lg 
                    {% if message.tags == 'success' %}
                        bg-green-100 text-green-900 border-green-400
                    {% elif message.tags == 'error' %}
                        bg-red-100 text-red-900 border-red-400
                    {% elif message.tags == 'info' %}
                        bg-blue-100 text-blue-900 border-blue-400
                    {% elif message.tags == 'warning' %}
                        bg-yellow-100 text-yellow-900 border-yellow-400
                    {% endif %}
                ">
                    {{ message }}
                </li>
            {% endfor %} 
        </ul>
    {% endif %}
        <div class="flex justify-between items-center border-b border-gray-200 pb-6 mb-8">
            <h1 class="text-3xl font-semibold text-gray-800">Borrowed List</h1>
            <div class="flex items-center space-x-6">
                <a href="{% url 'secretary:item-borrow' %}" class="text-indigo-500 hover:text-indigo-700">Borrow Item</a>
            </div>
        </div>
        <div class="mb-8 flex items-center">
            <form method="GET" action="" class="flex items-center space-x-4">
                {% csrf_token %}
                <input type="text" name="search_term" placeholder="Search..." class="border rounded-l py-2 px-4 focus:outline-none focus:ring focus:border-blue-300">
                <button type="submit" class="bg-blue-500 text-white py-2 px-4 rounded-r hover:bg-blue-600">Search</button>
            </form>
        </div>
        
        <div class="overflow-x-auto">
            <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                <table class="min-w-full divide-y divide-gray-200">
                    <thead class="bg-gray-50">
                        <tr>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Borrower
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Item
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Description
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Quantity
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Price
                            </th>
                            {% if request.user.is_secretary %}
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Action
                            </th>
                        {% endif %}
                        </tr>
                    </thead>
                    <tbody>
                        {% for borroweditem in object_list %}
                            <tr class="bg-white">
                                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                                    {{ borroweditem.borrower }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                                    <a href="{% url 'secretary:item-detail' borroweditem.item.pk %}" class="text-blue-500 hover:underline">{{ borroweditem.item }}</a>
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-500">
                                    {{ borroweditem.item.description }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-500">
                                    {{ borroweditem.quantity }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-500">
                                    ₱{{ borroweditem.item.price|floatformat }}
                                </td>                                
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                    <form method="post" action="{% url 'secretary:return-item' borroweditem.pk %}">
                                        {% csrf_token %}
                                        <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Return</button>
                                    </form>
                                </td>

                            </tr>
                        {% empty %}
                            <tr>
                                <td colspan="5" class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                    There are currently no Equipments
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>
<script src="https://cdn.jsdelivr.net/npm/quagga/dist/quagga.min.js"></script>
{% endblock content %}

capstone_project-django/secretary/templates/secretary/item_borrow.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container mx-auto h-full flex justify-center items-center">
        <div class="max-w-md mx-auto">
            <h1 class="text-3xl font-semibold text-gray-800 mb-6">Borrow Item</h1>
            <form method="post" class="mx-auto">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded mt-4">Confirm</button>
            </form>
        </div>
    </div>
{% endblock content %}

capstone_project-django/secretary/templates/secretary/item_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container mx-auto h-full flex justify-center items-center">
        <div class="max-w-md mx-auto">
            <h1 class="text-3xl font-semibold text-gray-800 mb-6">Add Item</h1>
            <form method="post" class="mx-auto">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded mt-4">Add</button>
            </form>
        </div>
    </div>
{% endblock content %}

capstone_project-django/secretary/templates/secretary/item_detail.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-700 body-font">
    <div class="container px-5 py-24 mx-auto flex flex-wrap">
        <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
            <div>
                <h1 class="text-4xl text-gray-800">Batch Item </h1>
            </div>
            <div>
                <a href="{% url 'secretary:item-list' %}" class="text-indigo-500 hover:text-indigo-700">Back to Item List</a>
            </div>
        </div>

        <div class="flex flex-col w-full">
            <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
                <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                    <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                        <table class="min-w-full divide-y divide-gray-200">
                            <thead class="bg-gray-50">
                                <tr>
                                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        Name
                                    </th>
                                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        Description
                                    </th>
                                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        Price
                                    </th>
                                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        Batch ID
                                    </th>
                                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        Item ID
                                    </th>
                                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        QR Code
                                    </th>
                                    
                                </tr>
                            </thead>
                            <tbody>
                                {% for batch_item in batch_items %}
                                    <tr class="bg-white">
                                        <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                                            <a href="{% url 'secretary:item-detail' batch_item.pk %}">{{ batch_item.name }}</a>
                                        </td>
                                        <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                            {{ batch_item.description }}
                                        </td>
                                        <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                            {{ batch_item.price }}
                                        </td>
                                        <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                            {{ batch_item.batch_id }}
                                        </td>
                                        <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                            {{ batch_item.unique_identifier }}
                                        </td>
                                        <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                            <img src="{{ qr_code_url }}" alt="QR Code" width="100" height="100">
                                        </td>
                                    </tr>
                                {% empty %}
                                    <tr>
                                        <td colspan="5" class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900 text-center">
                                            No items available.
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

capstone_project-django/secretary/templates/secretary/item_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<section class="text-gray-700 body-font">
    <div class="container px-5 py-12 mx-auto">
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li class="mb-2 px-4 py-2 rounded-lg 
                    {% if message.tags == 'success' %}
                        bg-green-100 text-green-900 border-green-400
                    {% elif message.tags == 'error' %}
                        bg-red-100 text-red-900 border-red-400
                    {% elif message.tags == 'info' %}
                        bg-blue-100 text-blue-900 border-blue-400
                    {% elif message.tags == 'warning' %}
                        bg-yellow-100 text-yellow-900 border-yellow-400
                    {% endif %}
                ">
                    {{ message }}
                </li>
            {% endfor %} 
        </ul>
    {% endif %}
        <div class="flex justify-between items-center border-b border-gray-200 pb-6 mb-8">
            <h1 class="text-3xl font-semibold text-gray-800">Items</h1>
            <div class="flex items-center space-x-6">
                <a href="{% url 'secretary:item-new' %}" class="text-indigo-500 hover:text-indigo-700">Add Item</a>
            </div>
        </div>
        <div class="mb-8 flex items-center">
            <form method="GET" action="" class="flex items-center space-x-4">
                {% csrf_token %}
                <input type="text" name="search_term" placeholder="Search..." class="border rounded-l py-2 px-4 focus:outline-none focus:ring focus:border-blue-300">
                <button type="submit" class="bg-blue-500 text-white py-2 px-4 rounded-r hover:bg-blue-600">Search</button>
            </form>
        </div>
        
        <div class="overflow-x-auto">
            <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                <table class="min-w-full divide-y divide-gray-200">
                    <thead class="bg-gray-50">
                        <tr>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Name
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Category
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Description
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Quantity
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Price
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Batch ID
                            </th>
                            {% if request.user.is_secretary %}
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Action
                            </th>
                            {% endif %}
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in object_list %}
                            <tr class="bg-white">
                                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                                    <a href="{% url 'secretary:item-detail' item.pk %}">{{ item.name }}</a>
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                    {{ item.category }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                    {{ item.description }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                    {{ item.quantity }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                    {{ item.price }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                    {{ item.batch_id }}
                                </td>                                     
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                    <form method="get" action="{% url 'secretary:item-update' item.pk %}">
                                        {% csrf_token %}
                                        <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Update</button>
                                    </form>
                                 </td>
                            </tr>
                        {% empty %}
                            <tr>
                                <td colspan="5" class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                    There are currently no Items
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>
<script src="https://cdn.jsdelivr.net/npm/quagga/dist/quagga.min.js"></script>
{% endblock content %}