capstone_project-django/eims/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from secretary.views import LandingPageView, ProfileView
from users.views import LoginView, LogoutView
from secretary.views import ExportCSVView




urlpatterns = [
    path('admin/', admin.site.urls), 
    path('', LandingPageView.as_view(), name="landing-page"),
    path('profile/', ProfileView.as_view(), name="profile"),
    path('item/', include('secretary.urls', namespace='secretary')),
    path('user/', include('users.urls', namespace='users')),
    path('room/', include('rooms.urls', namespace='rooms')),
    path('staffs/', include('staffs.urls', namespace='staffs')),
    path('equipment/', include('rlab.urls', namespace='equipments')),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('export-csv/', ExportCSVView.as_view(), name='export-csv'),
    
    

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

capstone_project-django/users/urls.py
from django.urls import path
from django.shortcuts import redirect
from . import views

from .views import (

        UserListView, UserCreateView, UserUpdateView
)

app_name = 'users'

urlpatterns = [
    path('', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('user_list/', UserListView.as_view(), name='user-list'),
    path('user/', UserCreateView.as_view(), name='new-user'),
    path('user/<int:pk>/', UserUpdateView.as_view(), name='user-update'),
    path('my-redirect/', lambda request: redirect('admin:index'), name='my-redirect'),

]

capstone_project-django/logins/models.py
from django.db import models

# Create your models here.

capstone_project-django/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from rooms.models import Department
    
class User(AbstractUser):
    is_superuser = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    is_secretary = models.BooleanField(default=False)
    is_dean = models.BooleanField(default=False)
    department = models.ForeignKey(Department, on_delete=models.CASCADE, blank=True, null=True)
    contact_number = models.CharField(max_length=20, blank=True, null=True)
    
        
    def user_type(self):
        if self.is_admin:
            return "Admin"
        elif self.is_secretary:
            return "Secretary"
        elif self.is_dean:
            return "Dean"
        elif self.is_superuser:
            return "Superuser"
        else:
            return "Staff"

    def __str__(self):
        return f"{self.first_name} {self.last_name} ({self.user_type()})"

capstone_project-django/users/forms.py
from django import forms
from django.contrib.auth import get_user_model

User = get_user_model()

class UserModelForm(forms.ModelForm):
    # Define a field for user_type as a ChoiceField
    

    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
            'password',
            'department',
            'contact_number',
            'is_admin',
            'is_secretary',
            'is_dean',
        ]

class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
            'department',
            'contact_number',
            'is_active',
            'is_admin',
            'is_secretary',
            'is_dean',
        ]

capstone_project-django/logins/views.py
from django.shortcuts import render

# Create your views here.

capstone_project-django/users/views.py
from django.contrib import messages
from django.conf import settings
from django.shortcuts import get_object_or_404, render , redirect
from django.contrib.auth.views import LoginView as AuthLoginView
from django.contrib.auth import authenticate, login as auth_login, logout
from django.urls import reverse_lazy
from django.utils import timezone
from django.http import HttpResponse
from django.views import generic
from users.mixins import AdminRequiredMixin
from django.core.mail import send_mail
from .models import User
from .forms import UserModelForm, UserUpdateForm


class LoginView(AuthLoginView):
    template_name = 'users/login.html'
    
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            user = request.user
            if user.is_superuser:
                return redirect ("admin/")
            elif user.is_secretary:
                return redirect ("profile/")
            else:
                return redirect ("home/")
        else:
            return super().get(request, *args, **kwargs)
        
class LogoutView(AuthLoginView):
    url = reverse_lazy('login')

    def get(self, request, *args, **kwargs):
        logout(request)
        if not request.user.is_authenticated:
            return redirect('login')
        else:
            return super().get(request, *args, **kwargs)
        

class UserListView(AdminRequiredMixin, generic.ListView):
    model = User
    template_name = 'users/user_list.html'

    def get_queryset(self):
        return User.objects.all()

class UserCreateView(AdminRequiredMixin, generic.CreateView):
    form_class = UserModelForm
    template_name = 'users/new_user.html'
    success_url = reverse_lazy('users:user-list')

    def form_valid(self, form):
    # Save the user
        user = form.save(commit=False)
        user.set_password(form.cleaned_data['password'])  # Hash the password
        user.save()

    # Send invitation email
        subject = "EIMS Capstone Invitation"
        message = "You are invited to be a Staff in EIMS Capstone"
        from_email = "eims@test.com"
        recipient_list = [user.email]
        send_mail(subject, message, from_email, recipient_list)

        return super().form_valid(form)

class UserUpdateView(AdminRequiredMixin, generic.UpdateView):
    model = User
    form_class = UserUpdateForm
    template_name = 'users/user_update.html'
    success_url = reverse_lazy('users:user-list')

    def form_valid(self, form):
        messages.info(self.request, "You have successfully updated this User.")
        return super().form_valid(form)



        

capstone_project-django/users/templates/users/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>
<body>
    <div class="container">
        <div class="center">
            <h1>Equipment Information Management System</h1>
            <img src="{% static 'img/cmas.png' %}" alt="CMAS Logo">

            <form method="post">
                {% csrf_token %}
                <div class="text-field">
                    <input type="text" name="username" required placeholder="Username">
                    <input type="password" name="password" required placeholder="Password">
                    <input type="submit" name="submit" value="Login" class="form-btn">    
                </div>
            </form>
        </div>
    </div>
</body>
</html>

capstone_project-django/users/templates/users/logout.html
<form action="{% url 'logout' %}" method="post">
    <input type="hidden" name="next" value="{{ request.path }}">
    {% csrf_token %}
    <button type="submit">Logout</button>
</form>

capstone_project-django/users/templates/users/new_user.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container mx-auto h-full flex justify-center items-center">
        <div class="max-w-md mx-auto">
            <h1 class="text-3xl font-semibold text-gray-800 mb-6">Add User</h1>
            <form method="post" class="mx-auto">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded mt-4">Add</button>
            </form>
        </div>
    </div>
{% endblock content %}

capstone_project-django/users/templates/users/user_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<section class="text-gray-700 body-font">
    <div class="container px-5 py-12 mx-auto">
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li class="mb-2 px-4 py-2 rounded-lg 
                    {% if message.tags == 'success' %}
                        bg-green-100 text-green-900 border-green-400
                    {% elif message.tags == 'error' %}
                        bg-red-100 text-red-900 border-red-400
                    {% elif message.tags == 'info' %}
                        bg-blue-100 text-blue-900 border-blue-400
                    {% elif message.tags == 'warning' %}
                        bg-yellow-100 text-yellow-900 border-yellow-400
                    {% endif %}
                ">
                    {{ message }}
                </li>
            {% endfor %} 
        </ul>
    {% endif %}
        <div class="flex justify-between items-center border-b border-gray-200 pb-6 mb-8">
            <h1 class="text-3xl font-semibold text-gray-800">Users</h1>
            <div class="flex items-center space-x-6">
                <a href="{% url 'users:new-user' %}" class="text-indigo-500 hover:text-indigo-700">Add User</a>
            </div>
        </div>
        <div class="mb-8 flex items-center">
            <form method="GET" action="" class="flex items-center space-x-4">
                {% csrf_token %}
                <input type="text" name="search_term" placeholder="Search..." class="border rounded-l py-2 px-4 focus:outline-none focus:ring focus:border-blue-300">
                <button type="submit" class="bg-blue-500 text-white py-2 px-4 rounded-r hover:bg-blue-600">Search</button>
            </form>
        </div>
        
        <div class="overflow-x-auto">
            <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                <table class="min-w-full divide-y divide-gray-200">
                    <thead class="bg-gray-50">
                        <tr>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Username
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Firstname
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Lastname
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                             Deparment   
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            User Type
                            </th>
                            {% if request.user.is_admin %}
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Action
                            </th>
                            {% endif %}
                        </tr>
                    </thead>
                    <tbody>
                        {% for user in object_list %}
                            <tr class="bg-white">
                                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                                    {{ user.username }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                                    {{ user.first_name }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                                    {{ user.last_name }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                                    {{ user.department }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                                    {{ user.user_type }}
                                </td>                  
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                        <form method="get" action="{% url 'users:user-update' user.pk %}">
                                            {% csrf_token %}
                                            <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Update</button>           
                                        </form>
                                 </td>
                            </tr>
                        {% empty %}

                        <p>There are currently no Staff</p>

                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>
<script src="https://cdn.jsdelivr.net/npm/quagga/dist/quagga.min.js"></script>
{% endblock content %}

capstone_project-django/users/templates/users/user_update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container mx-auto h-full flex justify-center items-center">
        <div class="max-w-md mx-auto">
            <h1 class="text-3xl font-semibold text-gray-800 mb-6">Update User</h1>
            <form method="post" class="mx-auto">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded mt-4">Save</button>
            </form>
        </div>
    </div>
{% endblock content %}