capstone_project-django/eims/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from secretary.views import LandingPageView, ProfileView
from users.views import LoginView, LogoutView
from secretary.views import ExportCSVView




urlpatterns = [
    path('admin/', admin.site.urls), 
    path('', LandingPageView.as_view(), name="landing-page"),
    path('profile/', ProfileView.as_view(), name="profile"),
    path('item/', include('secretary.urls', namespace='secretary')),
    path('user/', include('users.urls', namespace='users')),
    path('room/', include('rooms.urls', namespace='rooms')),
    path('staffs/', include('staffs.urls', namespace='staffs')),
    path('equipment/', include('rlab.urls', namespace='equipments')),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('export-csv/', ExportCSVView.as_view(), name='export-csv'),
    
    

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

capstone_project-django/rlab/urls.py
from django.urls import path
from . views import (
    EquipmentListView, EquipmentCreateView, EquipmentDetailView, EquipmentUpdateView, EquipmentDeleteView, EquipmentBorrowView,
    BorrowEquipmentListView, ReturnEquipmentView
    
)

app_name = 'rlab'

urlpatterns = [
    
    path('', EquipmentListView.as_view(), name='equipment-list'),
    path('new/', EquipmentCreateView.as_view(), name='equipment-new'),
    path('<int:pk>/', EquipmentDetailView.as_view(), name='equipment-detail'),
    path('<int:pk>/update/', EquipmentUpdateView.as_view(), name='equipment-update'),
    path('<int:pk>/delete/', EquipmentDeleteView.as_view(), name='equipment-delete'),
    path('borrow/', EquipmentBorrowView.as_view(), name='equipment-borrow'),
    path('borrowed/', BorrowEquipmentListView.as_view(), name='eq-borrowed-list'),
    path('return-equipment/<int:pk>/', ReturnEquipmentView.as_view(), name='return-equipment'),
]

capstone_project-django/rlab/models.py
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import AbstractUser
from django.dispatch import receiver
from django.utils import timezone
from django.contrib.auth import get_user_model
from django.utils.dateformat import format
import uuid

from rooms.models import Room



User = get_user_model()

class Equipment(models.Model):
    name = models.CharField(max_length=100, blank=True, null=True)
    description = models.TextField(blank=True, null=True, max_length=1000)
    price = models.IntegerField(blank=True, null=True)
    quantity = models.IntegerField(default=1, blank=True, null=True)

    def __str__(self):
        return f"{self.name}"
    
class BorrowedEquipment(models.Model):
    borrower = models.ForeignKey(User, on_delete=models.CASCADE)
    equipment = models.ForeignKey(Equipment, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    date_borrowed = models.DateTimeField(auto_now_add=True)
    
    def return_equipment(self):

        # Add the quantity back to the equipment
        
        self.equipment.quantity += self.quantity  
        self.equipment.save()
        self.delete()

    def __str__(self):
        formatted_date = format(self.date_borrowed, 'N j, Y, P')
        return f"{formatted_date} - {self.borrower.first_name} {self.borrower.last_name} borrowed {self.equipment.description} of  {self.quantity} of {self.equipment.name} at {self.room.name} "

capstone_project-django/rlab/forms.py
from django import forms
from .models import Equipment, BorrowedEquipment
from users.models import User




class EquipmentForm(forms.ModelForm):
    class Meta:
        model = Equipment
        fields = ['name', 'description', 'price', 'quantity']



class EquipmentSearchForm(forms.ModelForm):
    class Meta:
        model = Equipment
        fields = ['name', 'description', 'price', 'quantity']




class BorrowEquipmentForm(forms.ModelForm):
    class Meta:
        model = BorrowedEquipment
        fields = ['borrower', 'equipment', 'quantity', 'room']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['borrower'].queryset = User.objects.filter(is_staff=True)
        self.fields['equipment'].queryset = Equipment.objects.exclude(quantity=0)
        

capstone_project-django/rlab/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse_lazy
from django.views import generic
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from users.mixins import DeanRequiredMixin
from .models import Equipment, BorrowedEquipment
from .forms import EquipmentSearchForm, EquipmentForm, BorrowEquipmentForm




class EquipmentListView(DeanRequiredMixin, generic.ListView):
    template_name = 'rlab/eq_list.html'
    queryset = Equipment.objects.all()
    form_class = EquipmentSearchForm  # Assign the form class to the view

    def get_queryset(self):
        queryset = super().get_queryset()  # Retrieve the original queryset

        # Check if a search term was submitted
        search_term = self.request.GET.get('search_term')
        if search_term:
            queryset = queryset.filter(name__icontains=search_term)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.form_class()  # Instantiate the form
        return context

class BorrowEquipmentListView(LoginRequiredMixin, generic.ListView):
    template_name = 'rlab/borrowed_list.html'
    

    def get_queryset(self):
        queryset = BorrowedEquipment.objects.all()
        if self.request.user.is_staff:
            return queryset.filter(borrower=self.request.user)
        return queryset

class EquipmentDetailView(DeanRequiredMixin, generic.DetailView):
    model = Equipment
    template_name = 'rlab/eq_detail.html'

class EquipmentCreateView(DeanRequiredMixin, generic.CreateView):
    template_name = 'rlab/eq_create.html'
    form_class = EquipmentForm
    success_url = reverse_lazy("rlab:equipment-list")

    def form_valid(self, form):
        messages.success(self.request, 'Equipment Added Successfully!')
        return super().form_valid(form)


class EquipmentUpdateView(DeanRequiredMixin, generic.UpdateView):
    model = Equipment
    form_class = EquipmentForm
    template_name = 'rlab/eq_update.html'
    success_url = reverse_lazy('rlab:equipment-list')

    def form_valid(self, form):
        messages.info(self.request, "You have successfully updated this Equipment.")
        return super().form_valid(form)
    
class EquipmentDeleteView(DeanRequiredMixin, generic.DeleteView):
    template_name = 'rlab/eq_delete.html'
    model = Equipment
    success_url = reverse_lazy("rlab:equipment-list")

class EquipmentBorrowView(DeanRequiredMixin, generic.CreateView):
    template_name = 'rlab/eq_borrow.html'
    form_class = BorrowEquipmentForm
    success_url = reverse_lazy('rlab:eq-borrowed-list')

    def form_valid(self, form):
        # Deduct the quantity from the item
        equipment = form.cleaned_data['equipment']
        quantity_borrowed = form.cleaned_data['quantity']

        if quantity_borrowed <= equipment.quantity:
            equipment.quantity -= quantity_borrowed
            equipment.save()

            # Save the borrowed item
            form.save()
            messages.success(self.request, 'Item borrowed successfully.')
            return super().form_valid(form)
        else:
            messages.error(self.request, 'Not enough quantity available.')
            return redirect('rlab:equipment-list')
        
class ReturnEquipmentView(DeanRequiredMixin, generic.RedirectView):
    permanent = False
    query_string = True
    pattern_name = 'eq-borrowed-list'
    

    def get(self, request, *args, **kwargs):
        borrowed_equipment = get_object_or_404(BorrowedEquipment, pk=kwargs['pk'])
        borrowed_equipment.return_equipment()
        messages.success(request, 'Item returned successfully.')
        success_url = reverse_lazy(self.pattern_name)
        return redirect('rlab:eq-borrowed-list')

capstone_project-django/rlab/templates/rlab/borrowed_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<section class="text-gray-700 body-font">
    <div class="container px-5 py-12 mx-auto">
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li class="mb-2 px-4 py-2 rounded-lg 
                        {% if message.tags == 'success' %}
                            bg-green-100 text-green-900 border-green-400
                        {% elif message.tags == 'error' %}
                            bg-red-100 text-red-900 border-red-400
                        {% elif message.tags == 'info' %}
                            bg-blue-100 text-blue-900 border-blue-400
                        {% elif message.tags == 'warning' %}
                            bg-yellow-100 text-yellow-900 border-yellow-400
                        {% endif %}
                    ">
                        {{ message }}
                    </li>
                {% endfor %} 
            </ul>
        {% endif %}
        <div class="flex justify-between items-center border-b border-gray-200 pb-6 mb-8">
            <h1 class="text-3xl font-semibold text-gray-800">Borrowed Items</h1>
            {% if request.user.is_dean %}
                <div class="flex items-center space-x-6">
                    <a href="{% url 'rlab:equipment-borrow' %}" class="text-indigo-500 hover:text-indigo-700">Borrow Item</a>
                    <a href="#" class="text-indigo-500 hover:text-indigo-700">Export</a>
                    <a href="#" class="text-indigo-500 hover:text-indigo-700">Scan</a>
                </div>
            {% endif %}
        </div>
        
        <div class="mb-8 flex items-center">
            <form method="GET" action="" class="flex items-center space-x-4">
                {% csrf_token %}
                <input type="text" name="search_term" placeholder="Search..." class="border rounded-l py-2 px-4 focus:outline-none focus:ring focus:border-blue-300">
                <button type="submit" class="bg-blue-500 text-white py-2 px-4 rounded-r hover:bg-blue-600">Search</button>
            </form>
        </div>
        
        <div>
            <div class="flex flex-col w-full">
                <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
                    <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                        <table class="min-w-full divide-y divide-gray-200">
                            <thead class="bg-gray-50">
                                <tr>
                                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        Date Borrowed
                                    </th>
                                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        Borrower
                                    </th>
                                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        Equipment
                                    </th>
                                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        Contact Number
                                    </th>
                                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        Quantity
                                    </th>
                                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        Room
                                    </th>
                                    {% if request.user.is_dean %}
                                        <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                            Action
                                        </th>
                                    {% endif %}
                                </tr>
                            </thead>
                            <tbody>
                                {% for borrowedequipment in object_list %}
                                    <tr class="bg-white">
                                        <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                            {{ borrowedequipment.date_borrowed }}
                                        </td>
                                        <td class="px-3 py-2 whitespace-nowrap text-sm font-medium text-gray-900">
                                            {{ borrowedequipment.borrower }}
                                        </td>
                                        <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                            <a href="#">{{ borrowedequipment.equipment }}</a>
                                        </td>
                                        <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                            {{ borrowedequipment.borrower.contact_number }}
                                        </td>
                                        <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                            {{ borrowedequipment.quantity }}
                                        </td>
                                        <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                            {{ borrowedequipment.room }}
                                        </td>       
                                        {% if request.user.is_dean %}                                 
                                        <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                            <form method="post" action="{% url 'rlab:return-equipment' borrowedequipment.pk %}">
                                                {% csrf_token %}
                                                <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Return</button>
                                            </form>
                                         </td>
                                        {% endif %}
                                    </tr>
                                {% empty %}
                                    <tr>
                                        <td colspan="5" class="px-6 py-4 whitespace-nowrap text-sm text-gray-500 block">
                                            There are currently no Equipments
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

capstone_project-django/rlab/templates/rlab/eq_borrow.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}


<div class="flex justify-center items-center h-screen">
    <div class="container mx-auto">
        <h1 class="text-3xl mb-6">Item Borrowing</h1>
        <form method="post" class="w-full max-w-md">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                Borrow Item
            </button>
        </form>
    </div>
</div>
{% endblock %}

capstone_project-django/rlab/templates/rlab/eq_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container mx-auto h-full flex justify-center items-center">
        <div class="max-w-md mx-auto">
            <h1 class="text-3xl font-semibold text-gray-800 mb-6">Add Item</h1>
            <form method="post" class="mx-auto">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded mt-4">Add</button>
            </form>
        </div>
    </div>
{% endblock content %}

capstone_project-django/rlab/templates/rlab/eq_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<section class="text-gray-700 body-font">
    <div class="container px-5 py-12 mx-auto">
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li class="mb-2 px-4 py-2 rounded-lg 
                    {% if message.tags == 'success' %}
                        bg-green-100 text-green-900 border-green-400
                    {% elif message.tags == 'error' %}
                        bg-red-100 text-red-900 border-red-400
                    {% elif message.tags == 'info' %}
                        bg-blue-100 text-blue-900 border-blue-400
                    {% elif message.tags == 'warning' %}
                        bg-yellow-100 text-yellow-900 border-yellow-400
                    {% endif %}
                ">
                    {{ message }}
                </li>
            {% endfor %} 
        </ul>
    {% endif %}
        <div class="flex justify-between items-center border-b border-gray-200 pb-6 mb-8">
            <h1 class="text-3xl font-semibold text-gray-800">Items</h1>
            <div class="flex items-center space-x-6">
                <a href="{% url 'rlab:equipment-new' %}" class="text-indigo-500 hover:text-indigo-700">Add Item</a>
                <a href="#" class="text-indigo-500 hover:text-indigo-700">Export</a>
                <a href="#" class="text-indigo-500 hover:text-indigo-700">Scan</a>
            </div>
        </div>
        <div class="mb-8 flex items-center">
            <form method="GET" action="" class="flex items-center space-x-4">
                {% csrf_token %}
                <input type="text" name="search_term" placeholder="Search..." class="border rounded-l py-2 px-4 focus:outline-none focus:ring focus:border-blue-300">
                <button type="submit" class="bg-blue-500 text-white py-2 px-4 rounded-r hover:bg-blue-600">Search</button>
            </form>
        </div>
        
        <div class="overflow-x-auto">
            <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                <table class="min-w-full divide-y divide-gray-200">
                    <thead class="bg-gray-50">
                        <tr>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Name
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Description
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Quantity
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Price
                            </th>
                            {% if request.user.is_dean %}
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Action
                            </th>
                            {% endif %}
                        </tr>
                    </thead>
                    <tbody>
                        {% for equipment in object_list %}
                            <tr class="bg-white">
                                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                                    <a href="{% url 'rlab:equipment-detail' equipment.pk %}" class="text-blue-500 hover:underline">{{ equipment.name }}</a>
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                    {{ equipment.description }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                    {{ equipment.quantity }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                    {{ equipment.price }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                    <form method="get" action="{% url 'rlab:equipment-update' equipment.pk %}">
                                        {% csrf_token %}
                                        <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Update</button>
                                    </form>
                                 </td>
                            </tr>
                        {% empty %}
                            <tr>
                                <td colspan="5" class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                    There are currently no Equipments
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>
<script src="https://cdn.jsdelivr.net/npm/quagga/dist/quagga.min.js"></script>
{% endblock content %}

capstone_project-django/rlab/templates/rlab/eq_update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container mx-auto h-full flex justify-center items-center">
        <div class="max-w-md mx-auto">
            <h1 class="text-3xl font-semibold text-gray-800 mb-6">Update Equipment</h1>
            <form method="post" class="mx-auto">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded mt-4">Save</button>
            </form>
        </div>
    </div>
{% endblock content %}